import type { IntakeTemplateDefinition } from '@/types/intake';

export const fewoStartTemplate: IntakeTemplateDefinition = {
  title: 'Fewo Startfragebogen Website-Ausrichtung',
  slug: 'fewo-startfragebogen-website-ausrichtung',
  description:
    'Kurzer Startfragebogen zur groben Ausrichtung, Struktur und Funktion einer Ferienwohnungs-Website.',
  status: 'active',
  version: 1,
  formType: 'custom',
  defaultLocale: 'de',
  sections: [
    {
      id: 'fewo-start-ausgangslage',
      title: 'Ausgangslage',
      order: 1,
      description: 'Kurze Einordnung des Projekts und der Ausgangssituation.',
      stepKey: 'ausgangslage',
      questions: [
        {
          id: 'fewo-start-project-type',
          key: 'projectType',
          fieldType: 'radio',
          label: 'Was trifft auf das Projekt am ehesten zu?',
          required: true,
          order: 1,
          options: [
            { label: 'Es soll eine neue Website entstehen', value: 'neu' },
            {
              label: 'Eine bestehende Website soll überarbeitet werden',
              value: 'relaunch',
            },
            {
              label: 'Es gibt bisher nur Buchungsplattformen oder Profile',
              value: 'plattformen',
            },
          ],
        },
        {
          id: 'fewo-start-main-goal',
          key: 'mainGoal',
          fieldType: 'checkbox-group',
          label: 'Was soll die Website hauptsächlich erreichen?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 2,
          options: [
            { label: 'Mehr direkte Anfragen', value: 'direkte-anfragen' },
            { label: 'Mehr Direktbuchungen', value: 'direktbuchungen' },
            {
              label: 'Professioneller auftreten',
              value: 'professioneller-auftritt',
            },
            {
              label: 'Bessere Sichtbarkeit bei Google',
              value: 'sichtbarkeit',
            },
            {
              label: 'Wichtige Infos übersichtlich bereitstellen',
              value: 'informationen',
            },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
      ],
    },
    {
      id: 'fewo-start-aufbau',
      title: 'Aufbau',
      order: 2,
      description: 'Welche Grundstruktur die Website haben soll.',
      stepKey: 'aufbau',
      questions: [
        {
          id: 'fewo-start-page-scope',
          key: 'pageScope',
          fieldType: 'radio',
          label: 'Wie umfangreich soll die Website ungefähr werden?',
          required: true,
          order: 1,
          options: [
            { label: 'Eher kompakt', value: 'kompakt' },
            { label: 'Mittelgroß', value: 'mittel' },
            { label: 'Etwas umfangreicher', value: 'umfangreich' },
          ],
        },
        {
          id: 'fewo-start-core-sections',
          key: 'coreSections',
          fieldType: 'checkbox-group',
          label: 'Welche Bereiche soll die Website auf jeden Fall haben?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 2,
          options: [
            { label: 'Startseite', value: 'startseite' },
            { label: 'Ausstattung', value: 'ausstattung' },
            { label: 'Preise', value: 'preise' },
            { label: 'Galerie', value: 'galerie' },
            { label: 'Lage & Umgebung', value: 'lage-umgebung' },
            { label: 'Kontakt / Anfrage', value: 'kontakt-anfrage' },
            { label: 'Bewertungen', value: 'bewertungen' },
            { label: 'FAQ', value: 'faq' },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
      ],
    },
    {
      id: 'fewo-start-funktionen',
      title: 'Funktionen',
      order: 3,
      description: 'Welche Kernfunktionen vorgesehen sind.',
      stepKey: 'funktionen',
      questions: [
        {
          id: 'fewo-start-features',
          key: 'features',
          fieldType: 'checkbox-group',
          label: 'Welche Funktionen soll die Website enthalten?',
          helpText: 'Mehrfachauswahl möglich.',
          required: false,
          order: 1,
          options: [
            { label: 'Kontaktformular', value: 'kontaktformular' },
            { label: 'Buchungsanfrage', value: 'buchungsanfrage' },
            { label: 'Verfügbarkeitskalender', value: 'kalender' },
            { label: 'Interaktive Karte', value: 'karte' },
            { label: 'WhatsApp-Kontakt', value: 'whatsapp' },
            { label: 'Mehrsprachigkeit', value: 'mehrsprachigkeit' },
          ],
        },
        {
          id: 'fewo-start-booking-flow',
          key: 'bookingFlow',
          fieldType: 'radio',
          label: 'Wie sollen Anfragen oder Buchungen grundsätzlich laufen?',
          required: true,
          order: 2,
          options: [
            {
              label: 'Über Kontaktformular oder Telefon',
              value: 'kontakt',
            },
            {
              label: 'Über Anfrageformular auf der Website',
              value: 'anfrageformular',
            },
            {
              label: 'Weiterleitung auf externe Plattform',
              value: 'extern',
            },
            { label: 'Noch offen', value: 'offen' },
          ],
        },
      ],
    },
    {
      id: 'fewo-start-prioritaeten',
      title: 'Prioritäten',
      order: 4,
      description: 'Was im ersten Schritt am wichtigsten ist.',
      stepKey: 'prioritaeten',
      questions: [
        {
          id: 'fewo-start-priority-focus',
          key: 'priorityFocus',
          fieldType: 'checkbox-group',
          label: 'Was ist im ersten Schritt besonders wichtig?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 1,
          options: [
            { label: 'Schnell online gehen', value: 'schnell-online' },
            {
              label: 'Professioneller und klarer Aufbau',
              value: 'klarer-aufbau',
            },
            { label: 'Mehr direkte Anfragen', value: 'anfragen' },
            { label: 'Gute mobile Nutzbarkeit', value: 'mobil' },
            {
              label: 'Später gut erweiterbar bleiben',
              value: 'erweiterbar',
            },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
        {
          id: 'fewo-start-notes',
          key: 'additionalNotes',
          fieldType: 'textarea',
          label:
            'Gibt es noch etwas Wichtiges zur groben Ausrichtung der Website?',
          placeholder: 'Freitext für zusätzliche Hinweise',
          required: false,
          order: 2,
        },
      ],
    },
  ],
};

export const fewoStructureTemplate: IntakeTemplateDefinition = {
  title: 'Grundsatzfragebogen Ferienwohnung Website-Struktur',
  slug: 'grundsatzfragebogen-ferienwohnung-struktur',
  description:
    'Kurzer Grundsatzfragebogen für Aufbau, Struktur und Funktionsumfang einer Ferienwohnungs-Website.',
  status: 'active',
  version: 1,
  formType: 'custom',
  defaultLocale: 'de',
  sections: [
    {
      id: 'fewo-structure-grundlagen',
      title: 'Grundlagen',
      order: 1,
      description: 'Grobe Einordnung des Projekts.',
      stepKey: 'grundlagen',
      questions: [
        {
          id: 'fewo-structure-project-type',
          key: 'projectType',
          fieldType: 'radio',
          label: 'Was ist der Ausgangspunkt für die Website?',
          required: true,
          order: 1,
          options: [
            {
              label: 'Es soll eine neue Website entstehen',
              value: 'neu',
            },
            {
              label: 'Eine bestehende Website soll überarbeitet werden',
              value: 'relaunch',
            },
            {
              label: 'Es gibt bisher nur Profile auf Plattformen',
              value: 'plattformen',
            },
          ],
        },
        {
          id: 'fewo-structure-existing-presence',
          key: 'existingPresenceUrl',
          fieldType: 'url',
          label: 'Falls schon etwas vorhanden ist: Website- oder Profil-Link',
          placeholder: 'https://...',
          required: false,
          order: 2,
        },
        {
          id: 'fewo-structure-main-goal',
          key: 'mainGoal',
          fieldType: 'checkbox-group',
          label: 'Was soll die Website hauptsächlich erreichen?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 3,
          options: [
            { label: 'Mehr direkte Anfragen', value: 'direkte-anfragen' },
            { label: 'Mehr Direktbuchungen', value: 'direktbuchungen' },
            {
              label: 'Professioneller Auftritt neben Airbnb oder Booking',
              value: 'professioneller-auftritt',
            },
            {
              label: 'Bessere Auffindbarkeit bei Google',
              value: 'sichtbarkeit',
            },
            {
              label: 'Gästen alle wichtigen Infos bereitstellen',
              value: 'informationen',
            },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
      ],
    },
    {
      id: 'fewo-structure-aufbau',
      title: 'Aufbau & Seiten',
      order: 2,
      description: 'Welche Bereiche und Seitentypen geplant sind.',
      stepKey: 'aufbau-seiten',
      questions: [
        {
          id: 'fewo-structure-page-areas',
          key: 'pageAreas',
          fieldType: 'checkbox-group',
          label: 'Welche Bereiche soll die Website enthalten?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 1,
          options: [
            { label: 'Startseite', value: 'startseite' },
            {
              label: 'Ferienwohnung im Überblick',
              value: 'ueberblick',
            },
            { label: 'Ausstattung', value: 'ausstattung' },
            { label: 'Preise', value: 'preise' },
            { label: 'Bildergalerie', value: 'galerie' },
            { label: 'Lage & Umgebung', value: 'lage-umgebung' },
            { label: 'Kontakt / Anfrage', value: 'kontakt-anfrage' },
            { label: 'Bewertungen', value: 'bewertungen' },
            { label: 'FAQ', value: 'faq' },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
        {
          id: 'fewo-structure-site-size',
          key: 'siteSize',
          fieldType: 'radio',
          label: 'Wie umfangreich soll die Website ungefähr werden?',
          required: true,
          order: 2,
          options: [
            {
              label: 'Eher kompakt, nur die wichtigsten Seiten',
              value: 'kompakt',
            },
            {
              label: 'Mittel, mit klar getrennten Bereichen',
              value: 'mittel',
            },
            {
              label: 'Etwas umfangreicher mit mehreren Unterseiten',
              value: 'umfangreicher',
            },
          ],
        },
        {
          id: 'fewo-structure-structure-notes',
          key: 'structureNotes',
          fieldType: 'textarea',
          label: 'Gibt es besondere Wünsche zum Aufbau oder zur Navigation?',
          placeholder:
            'Zum Beispiel einfache Struktur, wenige Klicks oder klare Trennung einzelner Bereiche',
          required: false,
          order: 3,
        },
      ],
    },
    {
      id: 'fewo-structure-funktionen',
      title: 'Funktionen',
      order: 3,
      description: 'Welche Module und Funktionen vorgesehen sind.',
      stepKey: 'funktionen',
      questions: [
        {
          id: 'fewo-structure-features',
          key: 'features',
          fieldType: 'checkbox-group',
          label: 'Welche Funktionen soll die Website enthalten?',
          helpText: 'Mehrfachauswahl möglich.',
          required: false,
          order: 1,
          options: [
            { label: 'Kontaktformular', value: 'kontaktformular' },
            { label: 'Buchungsanfrage', value: 'buchungsanfrage' },
            { label: 'Verfügbarkeitskalender', value: 'kalender' },
            { label: 'Interaktive Karte', value: 'karte' },
            {
              label: 'Anbindung an Airbnb oder Booking.com',
              value: 'plattform-link',
            },
            { label: 'WhatsApp-Kontakt', value: 'whatsapp' },
            { label: 'Mehrsprachigkeit', value: 'mehrsprachigkeit' },
            { label: 'Downloadbereich', value: 'downloads' },
            { label: 'Sonstige Funktion', value: 'sonstiges' },
          ],
        },
        {
          id: 'fewo-structure-booking-flow',
          key: 'bookingFlow',
          fieldType: 'radio',
          label: 'Wie sollen Anfragen oder Buchungen grundsätzlich laufen?',
          required: true,
          order: 2,
          options: [
            {
              label: 'Nur Kontaktaufnahme über Formular oder Telefon',
              value: 'kontakt',
            },
            {
              label: 'Anfrage über die Website, Abschluss später manuell',
              value: 'anfrage-manuell',
            },
            {
              label: 'Weiterleitung zu externer Buchungsplattform',
              value: 'extern',
            },
            { label: 'Noch nicht entschieden', value: 'offen' },
          ],
        },
        {
          id: 'fewo-structure-calendar-expectation',
          key: 'calendarExpectation',
          fieldType: 'radio',
          label: 'Welche Rolle soll ein Kalender spielen?',
          required: false,
          order: 3,
          options: [
            { label: 'Kein Kalender nötig', value: 'kein-kalender' },
            {
              label: 'Nur Verfügbarkeit anzeigen',
              value: 'verfuegbarkeit',
            },
            {
              label: 'Soll für Anfragen unterstützen',
              value: 'anfragen',
            },
            { label: 'Noch offen', value: 'offen' },
          ],
        },
      ],
    },
    {
      id: 'fewo-structure-prioritaeten',
      title: 'Ausrichtung & Prioritäten',
      order: 4,
      description: 'Was im ersten Schritt besonders wichtig ist.',
      stepKey: 'ausrichtung-prioritaeten',
      questions: [
        {
          id: 'fewo-structure-priority-focus',
          key: 'priorityFocus',
          fieldType: 'checkbox-group',
          label: 'Was soll im ersten Schritt Priorität haben?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 1,
          options: [
            { label: 'Schnell online gehen', value: 'schnell-online' },
            {
              label: 'Klarer und professioneller Aufbau',
              value: 'klarer-aufbau',
            },
            {
              label: 'Starker Fokus auf mobile Nutzung',
              value: 'mobil',
            },
            {
              label: 'Direkte Anfragen vereinfachen',
              value: 'anfragen',
            },
            {
              label: 'Später gut erweiterbar bleiben',
              value: 'erweiterbar',
            },
            {
              label: 'Technisch eher schlank bleiben',
              value: 'schlank',
            },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
        {
          id: 'fewo-structure-language-scope',
          key: 'languageScope',
          fieldType: 'radio',
          label:
            'Soll die Website eher einsprachig oder mehrsprachig gedacht werden?',
          required: true,
          order: 2,
          options: [
            { label: 'Nur deutsch', value: 'de' },
            { label: 'Deutsch und Englisch', value: 'de-en' },
            {
              label: 'Mehrsprachig mit weiterer Sprache',
              value: 'mehrsprachig',
            },
            { label: 'Noch offen', value: 'offen' },
          ],
        },
        {
          id: 'fewo-structure-notes',
          key: 'additionalNotes',
          fieldType: 'textarea',
          label: 'Gibt es noch etwas Wichtiges zum groben Aufbau der Website?',
          placeholder: 'Freitext für zusätzliche Hinweise',
          required: false,
          order: 3,
        },
      ],
    },
  ],
};

export const fewoDetailTemplate: IntakeTemplateDefinition = {
  title: 'Fewo Detailfragebogen Website-Umsetzung',
  slug: 'fewo-detailfragebogen-website-umsetzung',
  description:
    'Detaillierter Fragebogen für Ferienwohnungen mit Fokus auf Daten, Medien, Ausstattung und konkrete Website-Anforderungen.',
  status: 'active',
  version: 1,
  formType: 'custom',
  defaultLocale: 'de',
  sections: [
    {
      id: 'fewo-detail-basis',
      title: 'Basisdaten',
      order: 1,
      description: 'Allgemeine Informationen zur Ferienwohnung.',
      stepKey: 'basisdaten',
      questions: [
        {
          id: 'fewo-detail-name',
          key: 'propertyName',
          fieldType: 'text',
          label: 'Name der Ferienwohnung',
          required: true,
          order: 1,
        },
        {
          id: 'fewo-detail-slogan',
          key: 'propertySlogan',
          fieldType: 'text',
          label: 'Slogan oder kurzer Untertitel',
          required: false,
          order: 2,
        },
        {
          id: 'fewo-detail-address',
          key: 'propertyAddress',
          fieldType: 'textarea',
          label: 'Adresse oder Lage der Unterkunft',
          required: true,
          order: 3,
        },
        {
          id: 'fewo-detail-guests',
          key: 'maxGuests',
          fieldType: 'text',
          label: 'Für wie viele Personen ist die Unterkunft geeignet?',
          required: true,
          order: 4,
          validationRules: {
            pattern: '^[0-9]+$',
          },
        },
        {
          id: 'fewo-detail-target-groups',
          key: 'targetGroups',
          fieldType: 'checkbox-group',
          label: 'Welche Zielgruppen sollen angesprochen werden?',
          required: false,
          order: 5,
          options: [
            { label: 'Paare', value: 'paare' },
            { label: 'Familien', value: 'familien' },
            {
              label: 'Geschäftsreisende',
              value: 'geschaeftsreisende',
            },
            { label: 'Monteure', value: 'monteure' },
            {
              label: 'Urlauber mit Hund',
              value: 'urlauber-mit-hund',
            },
            { label: 'Gruppen', value: 'gruppen' },
            { label: 'Langzeitgäste', value: 'langzeitgaeste' },
          ],
        },
      ],
    },
    {
      id: 'fewo-detail-booking',
      title: 'Buchung & Kontakt',
      order: 2,
      description: 'Wie Gäste anfragen oder buchen sollen.',
      stepKey: 'buchung-kontakt',
      questions: [
        {
          id: 'fewo-detail-booking-channels',
          key: 'bookingChannels',
          fieldType: 'checkbox-group',
          label: 'Wie sollen Gäste buchen oder anfragen können?',
          required: true,
          order: 1,
          options: [
            {
              label: 'Direkte Buchungsanfrage über Formular',
              value: 'formular',
            },
            { label: 'Weiterleitung zu Airbnb', value: 'airbnb' },
            { label: 'Weiterleitung zu Booking.com', value: 'booking-com' },
            { label: 'Telefonische Anfrage', value: 'telefon' },
            { label: 'WhatsApp-Anfrage', value: 'whatsapp' },
            { label: 'E-Mail-Anfrage', value: 'email' },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
        {
          id: 'fewo-detail-phone',
          key: 'phone',
          fieldType: 'phone',
          label: 'Telefonnummer für Anfragen',
          required: false,
          order: 2,
        },
        {
          id: 'fewo-detail-email',
          key: 'email',
          fieldType: 'email',
          label: 'E-Mail-Adresse für Anfragen',
          required: true,
          order: 3,
        },
        {
          id: 'fewo-detail-airbnb-url',
          key: 'airbnbUrl',
          fieldType: 'url',
          label: 'Airbnb-Link',
          required: false,
          order: 4,
        },
        {
          id: 'fewo-detail-booking-url',
          key: 'bookingUrl',
          fieldType: 'url',
          label: 'Booking.com-Link',
          required: false,
          order: 5,
        },
      ],
    },
    {
      id: 'fewo-detail-property',
      title: 'Unterkunft & Ausstattung',
      order: 3,
      description: 'Details zur Ferienwohnung und zur Ausstattung.',
      stepKey: 'unterkunft-ausstattung',
      questions: [
        {
          id: 'fewo-detail-description',
          key: 'propertyDescription',
          fieldType: 'textarea',
          label: 'Kurzbeschreibung der Ferienwohnung',
          required: true,
          order: 1,
        },
        {
          id: 'fewo-detail-usp',
          key: 'uniqueSellingPoints',
          fieldType: 'textarea',
          label: 'Was macht die Unterkunft besonders?',
          required: false,
          order: 2,
        },
        {
          id: 'fewo-detail-amenities',
          key: 'amenities',
          fieldType: 'checkbox-group',
          label: 'Welche Ausstattung ist vorhanden?',
          required: false,
          order: 3,
          options: [
            { label: 'WLAN', value: 'wlan' },
            { label: 'Küche', value: 'kueche' },
            { label: 'Parkplatz', value: 'parkplatz' },
            { label: 'Waschmaschine', value: 'waschmaschine' },
            { label: 'Trockner', value: 'trockner' },
            { label: 'Balkon', value: 'balkon' },
            { label: 'Terrasse', value: 'terrasse' },
            { label: 'Garten', value: 'garten' },
            { label: 'Smart-TV', value: 'smart-tv' },
            { label: 'Kaffeemaschine', value: 'kaffeemaschine' },
            { label: 'Geschirrspüler', value: 'geschirrspueler' },
            { label: 'Klimaanlage', value: 'klimaanlage' },
            { label: 'Kinderbett', value: 'kinderbett' },
            {
              label: 'Haustiere erlaubt',
              value: 'haustiere-erlaubt',
            },
            {
              label: 'Nichtraucherunterkunft',
              value: 'nichtraucherunterkunft',
            },
          ],
        },
        {
          id: 'fewo-detail-rooms',
          key: 'rooms',
          fieldType: 'textarea',
          label: 'Bitte Räume, Betten und Badezimmer beschreiben',
          required: true,
          order: 4,
        },
      ],
    },
    {
      id: 'fewo-detail-media',
      title: 'Bilder & Website-Inhalte',
      order: 4,
      description: 'Material und Funktionswünsche für die Website.',
      stepKey: 'bilder-website',
      questions: [
        {
          id: 'fewo-detail-images',
          key: 'propertyImages',
          fieldType: 'file',
          label: 'Bilder der Ferienwohnung hochladen',
          required: true,
          order: 1,
          validationRules: {
            allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
            maxFileSize: 15728640,
            allowMultiple: true,
          },
        },
        {
          id: 'fewo-detail-logo',
          key: 'logo',
          fieldType: 'file',
          label: 'Logo hochladen, falls vorhanden',
          required: false,
          order: 2,
          validationRules: {
            allowedMimeTypes: [
              'image/jpeg',
              'image/png',
              'image/svg+xml',
              'image/webp',
            ],
            maxFileSize: 5242880,
            allowMultiple: false,
          },
        },
        {
          id: 'fewo-detail-website-features',
          key: 'websiteFeatures',
          fieldType: 'checkbox-group',
          label: 'Was soll die Website enthalten?',
          helpText: 'Mehrfachauswahl möglich.',
          required: false,
          order: 3,
          options: [
            { label: 'Bildergalerie', value: 'bildergalerie' },
            { label: 'Interaktive Karte', value: 'karte' },
            {
              label: 'Verfügbarkeitskalender',
              value: 'verfuegbarkeitskalender',
            },
            { label: 'Buchungsanfrage', value: 'buchungsanfrage' },
            { label: 'FAQ-Bereich', value: 'faq' },
            { label: 'Gästebewertungen', value: 'bewertungen' },
            { label: 'Umgebungstipps', value: 'umgebungstipps' },
            { label: 'Preistabelle', value: 'preistabelle' },
            { label: 'Anfahrtsbeschreibung', value: 'anfahrt' },
            { label: 'Downloadbereich', value: 'downloads' },
            { label: 'Mehrsprachige Inhalte', value: 'mehrsprachig' },
            { label: 'Sonstiges', value: 'sonstiges' },
          ],
        },
        {
          id: 'fewo-detail-feature-notes',
          key: 'additionalNotes',
          fieldType: 'textarea',
          label: 'Gibt es noch zusätzliche Infos, Wünsche oder Besonderheiten?',
          helpText:
            'Hier ist Platz für alles, was bisher noch nicht abgefragt wurde.',
          placeholder: 'Freitext für weitere Hinweise',
          required: false,
          order: 4,
          validationRules: {
            maxLength: 3000,
          },
        },
      ],
    },
  ],
};

export const fewoTemplatePack: IntakeTemplateDefinition[] = [
  fewoStartTemplate,
  fewoStructureTemplate,
  fewoDetailTemplate,
];
