import type { IntakeTemplateDefinition } from '@/types/intake';

export const restaurantStartTemplate: IntakeTemplateDefinition = {
  title: 'Restaurant Startfragebogen Website-Ausrichtung',
  slug: 'restaurant-startfragebogen-website-ausrichtung',
  description:
    'Kurzer Startfragebogen zur groben Ausrichtung, Struktur und Funktion einer Restaurant-Website.',
  status: 'active',
  version: 1,
  formType: 'custom',
  defaultLocale: 'de',
  sections: [
    {
      id: 'restaurant-start-ausgangslage',
      title: 'Ausgangslage',
      order: 1,
      description: 'Kurze Einordnung des Restaurant-Projekts.',
      stepKey: 'ausgangslage',
      questions: [
        {
          id: 'restaurant-start-project-type',
          key: 'projectType',
          fieldType: 'radio',
          label: 'Was trifft auf das Projekt am ehesten zu?',
          required: true,
          order: 1,
          options: [
            { label: 'Es soll eine neue Website entstehen', value: 'neu' },
            {
              label: 'Eine bestehende Website soll überarbeitet werden',
              value: 'relaunch',
            },
            {
              label: 'Es gibt bisher nur Profile auf Google oder Plattformen',
              value: 'profile',
            },
          ],
        },
        {
          id: 'restaurant-start-main-goal',
          key: 'mainGoal',
          fieldType: 'checkbox-group',
          label: 'Was soll die Website hauptsächlich erreichen?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 2,
          options: [
            { label: 'Mehr Reservierungen', value: 'reservierungen' },
            { label: 'Mehr Sichtbarkeit vor Ort', value: 'sichtbarkeit' },
            { label: 'Speisekarte klar präsentieren', value: 'speisekarte' },
            {
              label: 'Professioneller Gesamtauftritt',
              value: 'professioneller-auftritt',
            },
            {
              label: 'Veranstaltungen oder Aktionen kommunizieren',
              value: 'events',
            },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
      ],
    },
    {
      id: 'restaurant-start-aufbau',
      title: 'Aufbau',
      order: 2,
      description: 'Welche Grundstruktur die Website haben soll.',
      stepKey: 'aufbau',
      questions: [
        {
          id: 'restaurant-start-page-scope',
          key: 'pageScope',
          fieldType: 'radio',
          label: 'Wie umfangreich soll die Website ungefähr werden?',
          required: true,
          order: 1,
          options: [
            { label: 'Eher kompakt', value: 'kompakt' },
            { label: 'Mittelgroß', value: 'mittel' },
            { label: 'Etwas umfangreicher', value: 'umfangreich' },
          ],
        },
        {
          id: 'restaurant-start-core-sections',
          key: 'coreSections',
          fieldType: 'checkbox-group',
          label: 'Welche Bereiche soll die Website auf jeden Fall haben?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 2,
          options: [
            { label: 'Startseite', value: 'startseite' },
            { label: 'Speisekarte', value: 'speisekarte' },
            { label: 'Über uns', value: 'ueber-uns' },
            { label: 'Reservierung', value: 'reservierung' },
            { label: 'Galerie', value: 'galerie' },
            { label: 'Events', value: 'events' },
            { label: 'Kontakt / Anfahrt', value: 'kontakt-anfahrt' },
            { label: 'Bewertungen', value: 'bewertungen' },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
      ],
    },
    {
      id: 'restaurant-start-funktionen',
      title: 'Funktionen',
      order: 3,
      description: 'Welche Kernfunktionen vorgesehen sind.',
      stepKey: 'funktionen',
      questions: [
        {
          id: 'restaurant-start-features',
          key: 'features',
          fieldType: 'checkbox-group',
          label: 'Welche Funktionen soll die Website enthalten?',
          helpText: 'Mehrfachauswahl möglich.',
          required: false,
          order: 1,
          options: [
            { label: 'Kontaktformular', value: 'kontaktformular' },
            { label: 'Online-Reservierung', value: 'online-reservierung' },
            { label: 'Interaktive Karte', value: 'karte' },
            { label: 'WhatsApp-Kontakt', value: 'whatsapp' },
            { label: 'Speisekarte als PDF', value: 'speisekarte-pdf' },
            { label: 'Mehrsprachigkeit', value: 'mehrsprachigkeit' },
          ],
        },
        {
          id: 'restaurant-start-reservation-flow',
          key: 'reservationFlow',
          fieldType: 'radio',
          label: 'Wie sollen Reservierungen grundsätzlich laufen?',
          required: true,
          order: 2,
          options: [
            { label: 'Über Telefon oder Kontaktformular', value: 'kontakt' },
            {
              label: 'Über ein Reservierungsformular auf der Website',
              value: 'formular',
            },
            {
              label: 'Über externes Reservierungssystem',
              value: 'extern',
            },
            { label: 'Noch offen', value: 'offen' },
          ],
        },
      ],
    },
    {
      id: 'restaurant-start-prioritaeten',
      title: 'Prioritäten',
      order: 4,
      description: 'Was im ersten Schritt am wichtigsten ist.',
      stepKey: 'prioritaeten',
      questions: [
        {
          id: 'restaurant-start-priority-focus',
          key: 'priorityFocus',
          fieldType: 'checkbox-group',
          label: 'Was ist im ersten Schritt besonders wichtig?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 1,
          options: [
            { label: 'Schnell online gehen', value: 'schnell-online' },
            {
              label: 'Professioneller und klarer Auftritt',
              value: 'klarer-aufbau',
            },
            { label: 'Mehr Reservierungen', value: 'reservierungen' },
            { label: 'Gute mobile Nutzbarkeit', value: 'mobil' },
            {
              label: 'Später gut erweiterbar bleiben',
              value: 'erweiterbar',
            },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
        {
          id: 'restaurant-start-notes',
          key: 'additionalNotes',
          fieldType: 'textarea',
          label:
            'Gibt es noch etwas Wichtiges zur groben Ausrichtung der Website?',
          placeholder: 'Freitext für zusätzliche Hinweise',
          required: false,
          order: 2,
        },
      ],
    },
  ],
};

export const restaurantStructureTemplate: IntakeTemplateDefinition = {
  title: 'Grundsatzfragebogen Restaurant Website-Struktur',
  slug: 'grundsatzfragebogen-restaurant-struktur',
  description:
    'Kurzer Grundsatzfragebogen für Aufbau, Struktur und Funktionsumfang einer Restaurant-Website.',
  status: 'active',
  version: 1,
  formType: 'custom',
  defaultLocale: 'de',
  sections: [
    {
      id: 'restaurant-structure-grundlagen',
      title: 'Grundlagen',
      order: 1,
      description: 'Grobe Einordnung des Gastronomie-Projekts.',
      stepKey: 'grundlagen',
      questions: [
        {
          id: 'restaurant-structure-project-type',
          key: 'projectType',
          fieldType: 'radio',
          label: 'Was ist der Ausgangspunkt für die Website?',
          required: true,
          order: 1,
          options: [
            { label: 'Es soll eine neue Website entstehen', value: 'neu' },
            {
              label: 'Eine bestehende Website soll überarbeitet werden',
              value: 'relaunch',
            },
            {
              label: 'Es gibt bisher nur Profile auf Google oder Plattformen',
              value: 'profile',
            },
          ],
        },
        {
          id: 'restaurant-structure-existing-presence',
          key: 'existingPresenceUrl',
          fieldType: 'url',
          label: 'Falls schon etwas vorhanden ist: Website- oder Profil-Link',
          placeholder: 'https://...',
          required: false,
          order: 2,
        },
        {
          id: 'restaurant-structure-main-goal',
          key: 'mainGoal',
          fieldType: 'checkbox-group',
          label: 'Was soll die Website hauptsächlich erreichen?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 3,
          options: [
            { label: 'Mehr Reservierungen', value: 'reservierungen' },
            { label: 'Mehr lokale Sichtbarkeit', value: 'sichtbarkeit' },
            { label: 'Speisekarte gut präsentieren', value: 'speisekarte' },
            {
              label: 'Veranstaltungen oder Aktionen sichtbar machen',
              value: 'events',
            },
            {
              label: 'Professionellen Gesamtauftritt stärken',
              value: 'professioneller-auftritt',
            },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
      ],
    },
    {
      id: 'restaurant-structure-aufbau',
      title: 'Aufbau & Seiten',
      order: 2,
      description: 'Welche Bereiche und Seitentypen geplant sind.',
      stepKey: 'aufbau-seiten',
      questions: [
        {
          id: 'restaurant-structure-page-areas',
          key: 'pageAreas',
          fieldType: 'checkbox-group',
          label: 'Welche Bereiche soll die Website enthalten?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 1,
          options: [
            { label: 'Startseite', value: 'startseite' },
            { label: 'Speisekarte', value: 'speisekarte' },
            { label: 'Mittagskarte oder Aktionen', value: 'aktionen' },
            { label: 'Über uns / Team', value: 'team' },
            { label: 'Reservierung', value: 'reservierung' },
            { label: 'Galerie', value: 'galerie' },
            { label: 'Events', value: 'events' },
            { label: 'Kontakt / Anfahrt', value: 'kontakt-anfahrt' },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
        {
          id: 'restaurant-structure-site-size',
          key: 'siteSize',
          fieldType: 'radio',
          label: 'Wie umfangreich soll die Website ungefähr werden?',
          required: true,
          order: 2,
          options: [
            {
              label: 'Eher kompakt, nur die wichtigsten Seiten',
              value: 'kompakt',
            },
            {
              label: 'Mittel, mit klar getrennten Bereichen',
              value: 'mittel',
            },
            {
              label: 'Etwas umfangreicher mit mehreren Unterseiten',
              value: 'umfangreicher',
            },
          ],
        },
        {
          id: 'restaurant-structure-structure-notes',
          key: 'structureNotes',
          fieldType: 'textarea',
          label: 'Gibt es besondere Wünsche zum Aufbau oder zur Navigation?',
          placeholder:
            'Zum Beispiel Fokus auf Reservierung, Aktionen, Speisekarte oder Events',
          required: false,
          order: 3,
        },
      ],
    },
    {
      id: 'restaurant-structure-funktionen',
      title: 'Funktionen',
      order: 3,
      description: 'Welche Module und Funktionen vorgesehen sind.',
      stepKey: 'funktionen',
      questions: [
        {
          id: 'restaurant-structure-features',
          key: 'features',
          fieldType: 'checkbox-group',
          label: 'Welche Funktionen soll die Website enthalten?',
          helpText: 'Mehrfachauswahl möglich.',
          required: false,
          order: 1,
          options: [
            { label: 'Kontaktformular', value: 'kontaktformular' },
            { label: 'Online-Reservierung', value: 'online-reservierung' },
            { label: 'Interaktive Karte', value: 'karte' },
            { label: 'WhatsApp-Kontakt', value: 'whatsapp' },
            { label: 'Speisekarte als PDF', value: 'speisekarte-pdf' },
            { label: 'Mehrsprachigkeit', value: 'mehrsprachigkeit' },
            { label: 'Eventkalender', value: 'eventkalender' },
            { label: 'Gutscheine', value: 'gutscheine' },
            { label: 'Sonstige Funktion', value: 'sonstiges' },
          ],
        },
        {
          id: 'restaurant-structure-reservation-flow',
          key: 'reservationFlow',
          fieldType: 'radio',
          label: 'Wie sollen Reservierungen grundsätzlich laufen?',
          required: true,
          order: 2,
          options: [
            {
              label: 'Nur Kontaktaufnahme über Telefon oder Formular',
              value: 'kontakt',
            },
            {
              label: 'Reservierungsformular auf der Website',
              value: 'formular',
            },
            {
              label: 'Weiterleitung zu externem Reservierungssystem',
              value: 'extern',
            },
            { label: 'Noch nicht entschieden', value: 'offen' },
          ],
        },
        {
          id: 'restaurant-structure-menu-presentation',
          key: 'menuPresentation',
          fieldType: 'radio',
          label: 'Wie soll die Speisekarte auf der Website dargestellt werden?',
          required: false,
          order: 3,
          options: [
            { label: 'Als fester Seiteninhalt', value: 'inhalt' },
            { label: 'Als PDF-Download', value: 'pdf' },
            { label: 'Beides', value: 'beides' },
            { label: 'Noch offen', value: 'offen' },
          ],
        },
      ],
    },
    {
      id: 'restaurant-structure-prioritaeten',
      title: 'Ausrichtung & Prioritäten',
      order: 4,
      description: 'Was im ersten Schritt besonders wichtig ist.',
      stepKey: 'ausrichtung-prioritaeten',
      questions: [
        {
          id: 'restaurant-structure-priority-focus',
          key: 'priorityFocus',
          fieldType: 'checkbox-group',
          label: 'Was soll im ersten Schritt Priorität haben?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 1,
          options: [
            { label: 'Schnell online gehen', value: 'schnell-online' },
            {
              label: 'Klarer und professioneller Auftritt',
              value: 'klarer-aufbau',
            },
            { label: 'Mehr Reservierungen', value: 'reservierungen' },
            { label: 'Starke mobile Nutzung', value: 'mobil' },
            { label: 'Später gut erweiterbar bleiben', value: 'erweiterbar' },
            { label: 'Technisch eher schlank bleiben', value: 'schlank' },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
        {
          id: 'restaurant-structure-language-scope',
          key: 'languageScope',
          fieldType: 'radio',
          label:
            'Soll die Website eher einsprachig oder mehrsprachig gedacht werden?',
          required: true,
          order: 2,
          options: [
            { label: 'Nur deutsch', value: 'de' },
            { label: 'Deutsch und Englisch', value: 'de-en' },
            {
              label: 'Mehrsprachig mit weiterer Sprache',
              value: 'mehrsprachig',
            },
            { label: 'Noch offen', value: 'offen' },
          ],
        },
        {
          id: 'restaurant-structure-notes',
          key: 'additionalNotes',
          fieldType: 'textarea',
          label: 'Gibt es noch etwas Wichtiges zum groben Aufbau der Website?',
          placeholder: 'Freitext für zusätzliche Hinweise',
          required: false,
          order: 3,
        },
      ],
    },
  ],
};

export const restaurantDetailTemplate: IntakeTemplateDefinition = {
  title: 'Restaurant Detailfragebogen Website-Umsetzung',
  slug: 'restaurant-detailfragebogen-website-umsetzung',
  description:
    'Detaillierter Fragebogen für Restaurants mit Fokus auf Konzept, Angebot, Reservierung und konkrete Website-Anforderungen.',
  status: 'active',
  version: 1,
  formType: 'custom',
  defaultLocale: 'de',
  sections: [
    {
      id: 'restaurant-detail-basis',
      title: 'Basisdaten',
      order: 1,
      description: 'Allgemeine Informationen zum Restaurant.',
      stepKey: 'basisdaten',
      questions: [
        {
          id: 'restaurant-detail-name',
          key: 'restaurantName',
          fieldType: 'text',
          label: 'Name des Restaurants',
          required: true,
          order: 1,
        },
        {
          id: 'restaurant-detail-slogan',
          key: 'restaurantSlogan',
          fieldType: 'text',
          label: 'Slogan oder kurzer Untertitel',
          required: false,
          order: 2,
        },
        {
          id: 'restaurant-detail-address',
          key: 'restaurantAddress',
          fieldType: 'textarea',
          label: 'Adresse und Standort',
          required: true,
          order: 3,
        },
        {
          id: 'restaurant-detail-cuisine',
          key: 'cuisineType',
          fieldType: 'text',
          label: 'Welche Küche oder welches Konzept bietet ihr an?',
          required: true,
          order: 4,
        },
        {
          id: 'restaurant-detail-target-groups',
          key: 'targetGroups',
          fieldType: 'checkbox-group',
          label: 'Welche Zielgruppen sollen besonders angesprochen werden?',
          required: false,
          order: 5,
          options: [
            { label: 'Mittagsgäste', value: 'mittagsgaeste' },
            { label: 'Abendgäste', value: 'abendgaeste' },
            { label: 'Familien', value: 'familien' },
            { label: 'Touristen', value: 'touristen' },
            { label: 'Business-Gäste', value: 'business' },
            { label: 'Event- oder Gruppenbuchungen', value: 'gruppen' },
          ],
        },
      ],
    },
    {
      id: 'restaurant-detail-offer',
      title: 'Angebot & Ablauf',
      order: 2,
      description: 'Was präsentiert werden soll und wie Reservierungen laufen.',
      stepKey: 'angebot-ablauf',
      questions: [
        {
          id: 'restaurant-detail-offer-description',
          key: 'offerDescription',
          fieldType: 'textarea',
          label: 'Wie würdet ihr euer Restaurant und Angebot kurz beschreiben?',
          required: true,
          order: 1,
        },
        {
          id: 'restaurant-detail-specials',
          key: 'specialHighlights',
          fieldType: 'textarea',
          label: 'Was macht das Restaurant besonders?',
          required: false,
          order: 2,
        },
        {
          id: 'restaurant-detail-services',
          key: 'services',
          fieldType: 'checkbox-group',
          label: 'Welche Angebote oder Services gibt es?',
          required: false,
          order: 3,
          options: [
            { label: 'Reservierung vor Ort', value: 'reservierung' },
            { label: 'Abholung / Take-away', value: 'take-away' },
            { label: 'Lieferung', value: 'lieferung' },
            { label: 'Events oder Feiern', value: 'events' },
            { label: 'Mittagstisch', value: 'mittagstisch' },
            { label: 'Außenbereich', value: 'aussenbereich' },
          ],
        },
        {
          id: 'restaurant-detail-opening-hours',
          key: 'openingHours',
          fieldType: 'textarea',
          label: 'Bitte Öffnungszeiten und wichtige Hinweise angeben',
          required: true,
          order: 4,
        },
      ],
    },
    {
      id: 'restaurant-detail-contact',
      title: 'Kontakt & Reservierung',
      order: 3,
      description: 'Wie Gäste Kontakt aufnehmen oder reservieren sollen.',
      stepKey: 'kontakt-reservierung',
      questions: [
        {
          id: 'restaurant-detail-contact-phone',
          key: 'phone',
          fieldType: 'phone',
          label: 'Telefonnummer für Reservierungen oder Anfragen',
          required: true,
          order: 1,
        },
        {
          id: 'restaurant-detail-contact-email',
          key: 'email',
          fieldType: 'email',
          label: 'E-Mail-Adresse für Anfragen',
          required: true,
          order: 2,
        },
        {
          id: 'restaurant-detail-reservation-mode',
          key: 'reservationMode',
          fieldType: 'radio',
          label: 'Wie sollen Reservierungen über die Website laufen?',
          required: true,
          order: 3,
          options: [
            { label: 'Nur Telefon oder E-Mail', value: 'kontakt' },
            { label: 'Formular auf der Website', value: 'formular' },
            { label: 'Externes Reservierungssystem', value: 'extern' },
            { label: 'Noch offen', value: 'offen' },
          ],
        },
        {
          id: 'restaurant-detail-reservation-url',
          key: 'reservationUrl',
          fieldType: 'url',
          label: 'Link zum externen Reservierungssystem, falls vorhanden',
          required: false,
          order: 4,
        },
      ],
    },
    {
      id: 'restaurant-detail-media',
      title: 'Bilder & Website-Inhalte',
      order: 4,
      description: 'Material und Funktionswünsche für die Website.',
      stepKey: 'bilder-website',
      questions: [
        {
          id: 'restaurant-detail-images',
          key: 'restaurantImages',
          fieldType: 'file',
          label: 'Bilder vom Restaurant hochladen',
          required: true,
          order: 1,
          validationRules: {
            allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
            maxFileSize: 15728640,
            allowMultiple: true,
          },
        },
        {
          id: 'restaurant-detail-menu-file',
          key: 'menuFile',
          fieldType: 'file',
          label: 'Speisekarte oder Getränkekarte hochladen, falls vorhanden',
          required: false,
          order: 2,
          validationRules: {
            allowedMimeTypes: [
              'application/pdf',
              'image/jpeg',
              'image/png',
              'image/webp',
            ],
            maxFileSize: 15728640,
            allowMultiple: false,
          },
        },
        {
          id: 'restaurant-detail-website-features',
          key: 'websiteFeatures',
          fieldType: 'checkbox-group',
          label: 'Was soll die Website enthalten?',
          helpText: 'Mehrfachauswahl möglich.',
          required: false,
          order: 3,
          options: [
            { label: 'Bildergalerie', value: 'bildergalerie' },
            { label: 'Interaktive Karte', value: 'karte' },
            { label: 'Online-Reservierung', value: 'online-reservierung' },
            { label: 'Eventbereich', value: 'events' },
            { label: 'Speisekarte als Download', value: 'speisekarte-pdf' },
            { label: 'Bewertungen', value: 'bewertungen' },
            { label: 'Mehrsprachige Inhalte', value: 'mehrsprachig' },
            { label: 'Sonstiges', value: 'sonstiges' },
          ],
        },
        {
          id: 'restaurant-detail-feature-notes',
          key: 'additionalNotes',
          fieldType: 'textarea',
          label: 'Gibt es noch zusätzliche Infos, Wünsche oder Besonderheiten?',
          helpText:
            'Hier ist Platz für alles, was bisher noch nicht abgefragt wurde.',
          placeholder: 'Freitext für weitere Hinweise',
          required: false,
          order: 4,
          validationRules: {
            maxLength: 3000,
          },
        },
      ],
    },
  ],
};

export const restaurantTemplatePack: IntakeTemplateDefinition[] = [
  restaurantStartTemplate,
  restaurantStructureTemplate,
  restaurantDetailTemplate,
];
