import type { IntakeTemplateDefinition } from '@/types/intake';

export const serviceStartTemplate: IntakeTemplateDefinition = {
  title: 'Dienstleister Startfragebogen Website-Ausrichtung',
  slug: 'dienstleister-startfragebogen-website-ausrichtung',
  description:
    'Kurzer Startfragebogen zur groben Ausrichtung, Struktur und Funktion einer Dienstleister-Website.',
  status: 'active',
  version: 1,
  formType: 'custom',
  defaultLocale: 'de',
  sections: [
    {
      id: 'service-start-ausgangslage',
      title: 'Ausgangslage',
      order: 1,
      description: 'Kurze Einordnung des Projekts und der aktuellen Situation.',
      stepKey: 'ausgangslage',
      questions: [
        {
          id: 'service-start-project-type',
          key: 'projectType',
          fieldType: 'radio',
          label: 'Was trifft auf das Projekt am ehesten zu?',
          required: true,
          order: 1,
          options: [
            { label: 'Es soll eine neue Website entstehen', value: 'neu' },
            {
              label: 'Eine bestehende Website soll überarbeitet werden',
              value: 'relaunch',
            },
            {
              label: 'Es gibt bisher nur eine einfache Webpräsenz oder Profile',
              value: 'basis-praesenz',
            },
          ],
        },
        {
          id: 'service-start-main-goal',
          key: 'mainGoal',
          fieldType: 'checkbox-group',
          label: 'Was soll die Website hauptsächlich erreichen?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 2,
          options: [
            { label: 'Mehr qualifizierte Anfragen', value: 'anfragen' },
            { label: 'Professioneller auftreten', value: 'auftritt' },
            { label: 'Leistungen klar erklären', value: 'leistungen' },
            { label: 'Mehr lokale Sichtbarkeit', value: 'sichtbarkeit' },
            { label: 'Mitarbeiter gewinnen', value: 'bewerber' },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
      ],
    },
    {
      id: 'service-start-aufbau',
      title: 'Aufbau',
      order: 2,
      description: 'Welche Grundstruktur die Website haben soll.',
      stepKey: 'aufbau',
      questions: [
        {
          id: 'service-start-page-scope',
          key: 'pageScope',
          fieldType: 'radio',
          label: 'Wie umfangreich soll die Website ungefähr werden?',
          required: true,
          order: 1,
          options: [
            { label: 'Eher kompakt', value: 'kompakt' },
            { label: 'Mittelgroß', value: 'mittel' },
            { label: 'Etwas umfangreicher', value: 'umfangreich' },
          ],
        },
        {
          id: 'service-start-core-sections',
          key: 'coreSections',
          fieldType: 'checkbox-group',
          label: 'Welche Bereiche soll die Website auf jeden Fall haben?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 2,
          options: [
            { label: 'Startseite', value: 'startseite' },
            { label: 'Leistungen', value: 'leistungen' },
            { label: 'Über uns / Team', value: 'ueber-uns' },
            { label: 'Referenzen', value: 'referenzen' },
            { label: 'Standorte oder Einsatzgebiete', value: 'standorte' },
            { label: 'Kontakt / Anfrage', value: 'kontakt-anfrage' },
            { label: 'Karriere', value: 'karriere' },
            { label: 'FAQ', value: 'faq' },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
      ],
    },
    {
      id: 'service-start-funktionen',
      title: 'Funktionen',
      order: 3,
      description: 'Welche Kernfunktionen vorgesehen sind.',
      stepKey: 'funktionen',
      questions: [
        {
          id: 'service-start-features',
          key: 'features',
          fieldType: 'checkbox-group',
          label: 'Welche Funktionen soll die Website enthalten?',
          helpText: 'Mehrfachauswahl möglich.',
          required: false,
          order: 1,
          options: [
            { label: 'Kontaktformular', value: 'kontaktformular' },
            { label: 'Rückrufanfrage', value: 'rueckruf' },
            { label: 'Termin- oder Anfrageformular', value: 'terminanfrage' },
            { label: 'Interaktive Karte', value: 'karte' },
            { label: 'WhatsApp-Kontakt', value: 'whatsapp' },
            { label: 'Mehrsprachigkeit', value: 'mehrsprachigkeit' },
          ],
        },
        {
          id: 'service-start-lead-flow',
          key: 'leadFlow',
          fieldType: 'radio',
          label: 'Wie sollen Interessenten grundsätzlich Kontakt aufnehmen?',
          required: true,
          order: 2,
          options: [
            { label: 'Über Telefon oder E-Mail', value: 'kontakt' },
            { label: 'Über ein Formular auf der Website', value: 'formular' },
            { label: 'Über mehrere Wege parallel', value: 'mehrere-wege' },
            { label: 'Noch offen', value: 'offen' },
          ],
        },
      ],
    },
    {
      id: 'service-start-prioritaeten',
      title: 'Prioritäten',
      order: 4,
      description: 'Was im ersten Schritt am wichtigsten ist.',
      stepKey: 'prioritaeten',
      questions: [
        {
          id: 'service-start-priority-focus',
          key: 'priorityFocus',
          fieldType: 'checkbox-group',
          label: 'Was ist im ersten Schritt besonders wichtig?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 1,
          options: [
            { label: 'Schnell online gehen', value: 'schnell-online' },
            {
              label: 'Professioneller und klarer Auftritt',
              value: 'klarer-aufbau',
            },
            { label: 'Mehr Anfragen', value: 'anfragen' },
            { label: 'Gute mobile Nutzbarkeit', value: 'mobil' },
            {
              label: 'Später gut erweiterbar bleiben',
              value: 'erweiterbar',
            },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
        {
          id: 'service-start-notes',
          key: 'additionalNotes',
          fieldType: 'textarea',
          label:
            'Gibt es noch etwas Wichtiges zur groben Ausrichtung der Website?',
          placeholder: 'Freitext für zusätzliche Hinweise',
          required: false,
          order: 2,
        },
      ],
    },
  ],
};

export const serviceStructureTemplate: IntakeTemplateDefinition = {
  title: 'Grundsatzfragebogen Dienstleister Website-Struktur',
  slug: 'grundsatzfragebogen-dienstleister-struktur',
  description:
    'Kurzer Grundsatzfragebogen für Aufbau, Struktur und Funktionsumfang einer Dienstleister-Website.',
  status: 'active',
  version: 1,
  formType: 'custom',
  defaultLocale: 'de',
  sections: [
    {
      id: 'service-structure-grundlagen',
      title: 'Grundlagen',
      order: 1,
      description: 'Grobe Einordnung des Dienstleister-Projekts.',
      stepKey: 'grundlagen',
      questions: [
        {
          id: 'service-structure-project-type',
          key: 'projectType',
          fieldType: 'radio',
          label: 'Was ist der Ausgangspunkt für die Website?',
          required: true,
          order: 1,
          options: [
            { label: 'Es soll eine neue Website entstehen', value: 'neu' },
            {
              label: 'Eine bestehende Website soll überarbeitet werden',
              value: 'relaunch',
            },
            {
              label: 'Es gibt bisher nur eine einfache Webpräsenz oder Profile',
              value: 'basis-praesenz',
            },
          ],
        },
        {
          id: 'service-structure-existing-presence',
          key: 'existingPresenceUrl',
          fieldType: 'url',
          label: 'Falls schon etwas vorhanden ist: Website- oder Profil-Link',
          placeholder: 'https://...',
          required: false,
          order: 2,
        },
        {
          id: 'service-structure-main-goal',
          key: 'mainGoal',
          fieldType: 'checkbox-group',
          label: 'Was soll die Website hauptsächlich erreichen?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 3,
          options: [
            { label: 'Mehr qualifizierte Anfragen', value: 'anfragen' },
            {
              label: 'Leistungen verständlicher erklären',
              value: 'leistungen',
            },
            { label: 'Mehr lokale Sichtbarkeit', value: 'sichtbarkeit' },
            { label: 'Mehr Vertrauen aufbauen', value: 'vertrauen' },
            { label: 'Bewerbungen fördern', value: 'bewerber' },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
      ],
    },
    {
      id: 'service-structure-aufbau',
      title: 'Aufbau & Seiten',
      order: 2,
      description: 'Welche Bereiche und Seitentypen geplant sind.',
      stepKey: 'aufbau-seiten',
      questions: [
        {
          id: 'service-structure-page-areas',
          key: 'pageAreas',
          fieldType: 'checkbox-group',
          label: 'Welche Bereiche soll die Website enthalten?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 1,
          options: [
            { label: 'Startseite', value: 'startseite' },
            { label: 'Leistungsübersicht', value: 'leistungsuebersicht' },
            { label: 'Einzelseiten pro Leistung', value: 'leistungen' },
            { label: 'Über uns / Team', value: 'team' },
            { label: 'Referenzen', value: 'referenzen' },
            { label: 'Standorte oder Einsatzgebiete', value: 'standorte' },
            { label: 'Kontakt / Anfrage', value: 'kontakt-anfrage' },
            { label: 'Karriere', value: 'karriere' },
            { label: 'FAQ', value: 'faq' },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
        {
          id: 'service-structure-site-size',
          key: 'siteSize',
          fieldType: 'radio',
          label: 'Wie umfangreich soll die Website ungefähr werden?',
          required: true,
          order: 2,
          options: [
            {
              label: 'Eher kompakt, nur die wichtigsten Seiten',
              value: 'kompakt',
            },
            {
              label: 'Mittel, mit klar getrennten Bereichen',
              value: 'mittel',
            },
            {
              label: 'Etwas umfangreicher mit mehreren Unterseiten',
              value: 'umfangreicher',
            },
          ],
        },
        {
          id: 'service-structure-structure-notes',
          key: 'structureNotes',
          fieldType: 'textarea',
          label: 'Gibt es besondere Wünsche zum Aufbau oder zur Navigation?',
          placeholder:
            'Zum Beispiel Fokus auf Leistungsseiten, Ortsseiten oder klare Conversion-Wege',
          required: false,
          order: 3,
        },
      ],
    },
    {
      id: 'service-structure-funktionen',
      title: 'Funktionen',
      order: 3,
      description: 'Welche Module und Funktionen vorgesehen sind.',
      stepKey: 'funktionen',
      questions: [
        {
          id: 'service-structure-features',
          key: 'features',
          fieldType: 'checkbox-group',
          label: 'Welche Funktionen soll die Website enthalten?',
          helpText: 'Mehrfachauswahl möglich.',
          required: false,
          order: 1,
          options: [
            { label: 'Kontaktformular', value: 'kontaktformular' },
            { label: 'Rückrufanfrage', value: 'rueckruf' },
            { label: 'Termin- oder Anfrageformular', value: 'terminanfrage' },
            { label: 'Interaktive Karte', value: 'karte' },
            { label: 'WhatsApp-Kontakt', value: 'whatsapp' },
            { label: 'Mehrsprachigkeit', value: 'mehrsprachigkeit' },
            { label: 'Karriereformular', value: 'karriereformular' },
            { label: 'Downloadbereich', value: 'downloads' },
            { label: 'Sonstige Funktion', value: 'sonstiges' },
          ],
        },
        {
          id: 'service-structure-lead-flow',
          key: 'leadFlow',
          fieldType: 'radio',
          label: 'Wie sollen Interessenten grundsätzlich Kontakt aufnehmen?',
          required: true,
          order: 2,
          options: [
            { label: 'Nur Telefon oder E-Mail', value: 'kontakt' },
            { label: 'Über ein Formular auf der Website', value: 'formular' },
            { label: 'Über mehrere Wege parallel', value: 'mehrere-wege' },
            { label: 'Noch nicht entschieden', value: 'offen' },
          ],
        },
        {
          id: 'service-structure-trust-elements',
          key: 'trustElements',
          fieldType: 'checkbox-group',
          label: 'Welche Vertrauenselemente sollen sichtbar werden?',
          helpText: 'Mehrfachauswahl möglich.',
          required: false,
          order: 3,
          options: [
            { label: 'Kundenstimmen', value: 'bewertungen' },
            { label: 'Referenzprojekte', value: 'referenzen' },
            { label: 'Siegel oder Zertifikate', value: 'zertifikate' },
            { label: 'Teamvorstellung', value: 'team' },
            { label: 'Fallbeispiele', value: 'fallbeispiele' },
          ],
        },
      ],
    },
    {
      id: 'service-structure-prioritaeten',
      title: 'Ausrichtung & Prioritäten',
      order: 4,
      description: 'Was im ersten Schritt besonders wichtig ist.',
      stepKey: 'ausrichtung-prioritaeten',
      questions: [
        {
          id: 'service-structure-priority-focus',
          key: 'priorityFocus',
          fieldType: 'checkbox-group',
          label: 'Was soll im ersten Schritt Priorität haben?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 1,
          options: [
            { label: 'Schnell online gehen', value: 'schnell-online' },
            {
              label: 'Klarer und professioneller Auftritt',
              value: 'klarer-aufbau',
            },
            { label: 'Mehr Anfragen', value: 'anfragen' },
            { label: 'Starke mobile Nutzung', value: 'mobil' },
            { label: 'Später gut erweiterbar bleiben', value: 'erweiterbar' },
            { label: 'Technisch eher schlank bleiben', value: 'schlank' },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
        {
          id: 'service-structure-language-scope',
          key: 'languageScope',
          fieldType: 'radio',
          label:
            'Soll die Website eher einsprachig oder mehrsprachig gedacht werden?',
          required: true,
          order: 2,
          options: [
            { label: 'Nur deutsch', value: 'de' },
            { label: 'Deutsch und Englisch', value: 'de-en' },
            {
              label: 'Mehrsprachig mit weiterer Sprache',
              value: 'mehrsprachig',
            },
            { label: 'Noch offen', value: 'offen' },
          ],
        },
        {
          id: 'service-structure-notes',
          key: 'additionalNotes',
          fieldType: 'textarea',
          label: 'Gibt es noch etwas Wichtiges zum groben Aufbau der Website?',
          placeholder: 'Freitext für zusätzliche Hinweise',
          required: false,
          order: 3,
        },
      ],
    },
  ],
};

export const serviceDetailTemplate: IntakeTemplateDefinition = {
  title: 'Dienstleister Detailfragebogen Website-Umsetzung',
  slug: 'dienstleister-detailfragebogen-website-umsetzung',
  description:
    'Detaillierter Fragebogen für Dienstleister mit Fokus auf Leistungen, Vertrauen, Kontaktwege und konkrete Website-Anforderungen.',
  status: 'active',
  version: 1,
  formType: 'custom',
  defaultLocale: 'de',
  sections: [
    {
      id: 'service-detail-basis',
      title: 'Basisdaten',
      order: 1,
      description: 'Allgemeine Informationen zum Unternehmen oder Anbieter.',
      stepKey: 'basisdaten',
      questions: [
        {
          id: 'service-detail-company-name',
          key: 'companyName',
          fieldType: 'company',
          label: 'Name des Unternehmens oder Dienstleisters',
          required: true,
          order: 1,
        },
        {
          id: 'service-detail-contact-person',
          key: 'contactPerson',
          fieldType: 'contactPerson',
          label: 'Ansprechpartner',
          required: true,
          order: 2,
        },
        {
          id: 'service-detail-address',
          key: 'companyAddress',
          fieldType: 'textarea',
          label: 'Adresse oder Hauptstandort',
          required: true,
          order: 3,
        },
        {
          id: 'service-detail-core-offer',
          key: 'coreOffer',
          fieldType: 'textarea',
          label: 'Welche Leistungen oder Angebote stehen im Mittelpunkt?',
          required: true,
          order: 4,
        },
        {
          id: 'service-detail-target-groups',
          key: 'targetGroups',
          fieldType: 'textarea',
          label: 'Welche Zielgruppen sollen besonders angesprochen werden?',
          required: false,
          order: 5,
        },
      ],
    },
    {
      id: 'service-detail-services',
      title: 'Leistungen & Einsatzgebiet',
      order: 2,
      description: 'Wie Leistungen strukturiert und präsentiert werden sollen.',
      stepKey: 'leistungen-einsatzgebiet',
      questions: [
        {
          id: 'service-detail-service-list',
          key: 'serviceList',
          fieldType: 'textarea',
          label: 'Welche Leistungen sollen auf der Website dargestellt werden?',
          required: true,
          order: 1,
        },
        {
          id: 'service-detail-service-priorities',
          key: 'servicePriorities',
          fieldType: 'checkbox-group',
          label: 'Welche Leistungsbereiche sind besonders wichtig?',
          helpText: 'Mehrfachauswahl möglich oder thematisch frei nutzbar.',
          required: false,
          order: 2,
          options: [
            { label: 'Kernleistungen', value: 'kernleistungen' },
            { label: 'Zusatzleistungen', value: 'zusatzleistungen' },
            { label: 'Spezialisierungen', value: 'spezialisierungen' },
            { label: 'Notfall- oder Sofortservice', value: 'sofortservice' },
            { label: 'Wartung / Betreuung', value: 'betreuung' },
          ],
        },
        {
          id: 'service-detail-service-area',
          key: 'serviceArea',
          fieldType: 'textarea',
          label: 'In welchen Orten, Regionen oder Gebieten seid ihr tätig?',
          required: false,
          order: 3,
        },
        {
          id: 'service-detail-trust-points',
          key: 'trustPoints',
          fieldType: 'textarea',
          label:
            'Welche Argumente oder Nachweise schaffen besonders Vertrauen?',
          required: false,
          order: 4,
        },
      ],
    },
    {
      id: 'service-detail-contact',
      title: 'Kontakt & Conversion',
      order: 3,
      description:
        'Wie Interessenten Kontakt aufnehmen und welche Ziele gesetzt sind.',
      stepKey: 'kontakt-conversion',
      questions: [
        {
          id: 'service-detail-phone',
          key: 'phone',
          fieldType: 'phone',
          label: 'Telefonnummer für Anfragen',
          required: true,
          order: 1,
        },
        {
          id: 'service-detail-email',
          key: 'email',
          fieldType: 'email',
          label: 'E-Mail-Adresse für Anfragen',
          required: true,
          order: 2,
        },
        {
          id: 'service-detail-contact-mode',
          key: 'contactMode',
          fieldType: 'checkbox-group',
          label: 'Welche Kontaktwege sollen angeboten werden?',
          helpText: 'Mehrfachauswahl möglich.',
          required: true,
          order: 3,
          options: [
            { label: 'Telefon', value: 'telefon' },
            { label: 'E-Mail', value: 'email' },
            { label: 'Kontaktformular', value: 'formular' },
            { label: 'WhatsApp', value: 'whatsapp' },
            { label: 'Rückrufanfrage', value: 'rueckruf' },
          ],
          validationRules: {
            minSelections: 1,
          },
        },
        {
          id: 'service-detail-primary-cta',
          key: 'primaryCta',
          fieldType: 'text',
          label: 'Was soll die wichtigste Handlungsaufforderung sein?',
          placeholder: 'Zum Beispiel Jetzt anfragen oder Rückruf sichern',
          required: false,
          order: 4,
        },
      ],
    },
    {
      id: 'service-detail-media',
      title: 'Bilder & Website-Inhalte',
      order: 4,
      description: 'Material und Funktionswünsche für die Website.',
      stepKey: 'bilder-website',
      questions: [
        {
          id: 'service-detail-images',
          key: 'companyImages',
          fieldType: 'file',
          label: 'Bilder oder Eindrücke hochladen',
          required: false,
          order: 1,
          validationRules: {
            allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
            maxFileSize: 15728640,
            allowMultiple: true,
          },
        },
        {
          id: 'service-detail-logo',
          key: 'logo',
          fieldType: 'file',
          label: 'Logo hochladen, falls vorhanden',
          required: false,
          order: 2,
          validationRules: {
            allowedMimeTypes: [
              'image/jpeg',
              'image/png',
              'image/svg+xml',
              'image/webp',
            ],
            maxFileSize: 5242880,
            allowMultiple: false,
          },
        },
        {
          id: 'service-detail-website-features',
          key: 'websiteFeatures',
          fieldType: 'checkbox-group',
          label: 'Was soll die Website enthalten?',
          helpText: 'Mehrfachauswahl möglich.',
          required: false,
          order: 3,
          options: [
            { label: 'Bildergalerie', value: 'bildergalerie' },
            { label: 'Interaktive Karte', value: 'karte' },
            { label: 'Kontaktformular', value: 'kontaktformular' },
            { label: 'Termin- oder Anfrageformular', value: 'terminanfrage' },
            { label: 'Referenzen', value: 'referenzen' },
            { label: 'Karrierebereich', value: 'karriere' },
            { label: 'Mehrsprachige Inhalte', value: 'mehrsprachig' },
            { label: 'Downloadbereich', value: 'downloads' },
            { label: 'Sonstiges', value: 'sonstiges' },
          ],
        },
        {
          id: 'service-detail-feature-notes',
          key: 'additionalNotes',
          fieldType: 'textarea',
          label: 'Gibt es noch zusätzliche Infos, Wünsche oder Besonderheiten?',
          helpText:
            'Hier ist Platz für alles, was bisher noch nicht abgefragt wurde.',
          placeholder: 'Freitext für weitere Hinweise',
          required: false,
          order: 4,
          validationRules: {
            maxLength: 3000,
          },
        },
      ],
    },
  ],
};

export const serviceTemplatePack: IntakeTemplateDefinition[] = [
  serviceStartTemplate,
  serviceStructureTemplate,
  serviceDetailTemplate,
];
