import type { IntakeTemplateDefinition } from '@/types/intake';

export const brandingTemplate: IntakeTemplateDefinition = {
  title: 'Branding- und Logo-Fragebogen',
  slug: 'branding-logo',
  description:
    'Basisvorlage fuer Branding-, Logo- und visuelle Positionierungsprojekte.',
  status: 'active',
  version: 1,
  formType: 'branding',
  defaultLocale: 'de',
  notificationConfig: {
    internalRecipients: [],
    internalSubject: 'Neuer Branding-Fragebogen eingegangen',
    internalTemplateKey: 'intake-branding-internal',
    customerConfirmationEnabled: true,
    customerSubject: 'Dein Branding-Briefing ist eingegangen',
    customerTemplateKey: 'intake-branding-customer',
  },
  sections: [
    {
      id: 'branding-basics',
      title: 'Unternehmen und Marke',
      order: 1,
      stepKey: 'basis',
      questions: [
        {
          id: 'branding-company-name',
          key: 'companyName',
          fieldType: 'company',
          label: 'Firmenname',
          required: true,
          order: 1,
        },
        {
          id: 'branding-contact-person',
          key: 'contactPerson',
          fieldType: 'contactPerson',
          label: 'Ansprechpartner',
          required: true,
          order: 2,
        },
        {
          id: 'branding-core-offer',
          key: 'coreOffer',
          fieldType: 'textarea',
          label: 'Wofuer steht das Unternehmen und was wird angeboten?',
          required: true,
          order: 3,
        },
        {
          id: 'branding-target-groups',
          key: 'targetGroups',
          fieldType: 'textarea',
          label: 'Wer sind die wichtigsten Zielgruppen?',
          required: true,
          order: 4,
        },
      ],
    },
    {
      id: 'branding-direction',
      title: 'Gestalterische Richtung',
      order: 2,
      stepKey: 'richtung',
      questions: [
        {
          id: 'branding-new-logo',
          key: 'newLogoRequested',
          fieldType: 'yes-no',
          label: 'Soll ein neues Logo entwickelt werden?',
          required: true,
          order: 1,
        },
        {
          id: 'branding-style',
          key: 'brandStyle',
          fieldType: 'checkbox-group',
          label: 'Welche Stilrichtung passt am besten?',
          required: false,
          order: 2,
          options: [
            { label: 'Klar / reduziert', value: 'minimal' },
            { label: 'Hochwertig / premium', value: 'premium' },
            { label: 'Modern / digital', value: 'modern' },
            { label: 'Persoenlich / nahbar', value: 'personal' },
          ],
        },
        {
          id: 'branding-colors',
          key: 'preferredColors',
          fieldType: 'text',
          label: 'Gibt es gewuenschte Farben oder No-Gos?',
          required: false,
          order: 3,
        },
        {
          id: 'branding-references',
          key: 'designReferences',
          fieldType: 'file',
          label: 'Referenzen, Moodboards oder bestehende Dateien',
          required: false,
          order: 4,
          validationRules: {
            allowMultiple: true,
          },
        },
      ],
    },
    {
      id: 'branding-scope',
      title: 'Umfang und Abschluss',
      order: 3,
      stepKey: 'abschluss',
      questions: [
        {
          id: 'branding-deliverables',
          key: 'deliverables',
          fieldType: 'checkbox-group',
          label: 'Welche Ergebnisse werden benoetigt?',
          required: true,
          order: 1,
          options: [
            { label: 'Logo', value: 'logo' },
            { label: 'Farbsystem', value: 'colors' },
            { label: 'Typografie-Definition', value: 'typography' },
            { label: 'Kurz-Styleguide', value: 'styleguide' },
          ],
        },
        {
          id: 'branding-priority',
          key: 'brandPriority',
          fieldType: 'priority',
          label: 'Was ist aktuell am wichtigsten?',
          required: false,
          order: 2,
        },
        {
          id: 'branding-consent',
          key: 'privacyConsent',
          fieldType: 'consent',
          label:
            'Ich stimme der Verarbeitung meiner Angaben fuer die Projektanfrage zu.',
          required: true,
          order: 3,
        },
      ],
    },
  ],
};
