import type { IntakeTemplateDefinition } from '@/types/intake';

export const websiteRelaunchTemplate: IntakeTemplateDefinition = {
  title: 'Website-Relaunch-Fragebogen',
  slug: 'website-relaunch',
  description:
    'Strukturierte Erstaufnahme für Relaunch-Projekte mit Fokus auf Ziele, Inhalte, Technik und Projektorganisation.',
  status: 'active',
  version: 1,
  formType: 'relaunch',
  defaultLocale: 'de',
  notificationConfig: {
    internalRecipients: [],
    internalSubject: 'Neuer Relaunch-Fragebogen eingegangen',
    internalTemplateKey: 'intake-relaunch-internal',
    customerConfirmationEnabled: true,
    customerSubject: 'Dein Relaunch-Briefing ist eingegangen',
    customerTemplateKey: 'intake-relaunch-customer',
  },
  sections: [
    {
      id: 'relaunch-basics',
      title: 'Projektbasis',
      order: 1,
      description: 'Grunddaten zum Unternehmen und zur Ausgangslage.',
      stepKey: 'basis',
      questions: [
        {
          id: 'relaunch-company-name',
          key: 'companyName',
          fieldType: 'company',
          label: 'Firmenname',
          required: true,
          order: 1,
        },
        {
          id: 'relaunch-contact-person',
          key: 'contactPerson',
          fieldType: 'contactPerson',
          label: 'Ansprechpartner',
          required: true,
          order: 2,
        },
        {
          id: 'relaunch-contact-email',
          key: 'contactEmail',
          fieldType: 'email',
          label: 'E-Mail',
          required: true,
          order: 3,
        },
        {
          id: 'relaunch-current-url',
          key: 'currentWebsiteUrl',
          fieldType: 'url',
          label: 'Aktuelle Website-URL',
          required: false,
          order: 4,
        },
        {
          id: 'relaunch-goals',
          key: 'projectGoals',
          fieldType: 'textarea',
          label: 'Was soll der Relaunch konkret verbessern?',
          required: true,
          order: 5,
          validationRules: {
            minLength: 20,
          },
        },
      ],
    },
    {
      id: 'relaunch-content',
      title: 'Inhalte und Umfang',
      order: 2,
      description: 'Bestehende Inhalte, neue Seiten und redaktioneller Bedarf.',
      stepKey: 'inhalte',
      questions: [
        {
          id: 'relaunch-content-status',
          key: 'contentStatus',
          fieldType: 'dropdown',
          label: 'Wie ist der Stand der vorhandenen Inhalte?',
          required: true,
          order: 1,
          options: [
            { label: 'Weitgehend vorhanden', value: 'mostly-ready' },
            { label: 'Teilweise vorhanden', value: 'partial' },
            { label: 'Muss komplett neu erstellt werden', value: 'new' },
          ],
        },
        {
          id: 'relaunch-copy-needed',
          key: 'copyCreationNeeded',
          fieldType: 'yes-no',
          label: 'Sollen Texte neu erstellt oder überarbeitet werden?',
          required: true,
          order: 2,
        },
        {
          id: 'relaunch-page-priorities',
          key: 'pagePriorities',
          fieldType: 'checkbox-group',
          label: 'Welche Bereiche haben Priorität?',
          required: false,
          order: 3,
          options: [
            { label: 'Startseite', value: 'home' },
            { label: 'Leistungsseiten', value: 'services' },
            { label: 'Branchen-/Zielseiten', value: 'industries' },
            { label: 'Kontakt / Conversion', value: 'contact' },
          ],
        },
        {
          id: 'relaunch-existing-files',
          key: 'existingBriefingFiles',
          fieldType: 'file',
          label: 'Vorhandene Briefings, Screenshots oder Dateien',
          required: false,
          order: 4,
          validationRules: {
            allowMultiple: true,
          },
        },
      ],
    },
    {
      id: 'relaunch-technical',
      title: 'Technik und Freigabe',
      order: 3,
      description: 'Technische Anforderungen, Termine und Einwilligung.',
      stepKey: 'technik',
      questions: [
        {
          id: 'relaunch-features',
          key: 'technicalFeatures',
          fieldType: 'checkbox-group',
          label: 'Welche Funktionen werden benötigt?',
          required: false,
          order: 1,
          options: [
            { label: 'Mehrsprachigkeit', value: 'multilingual' },
            { label: 'Blog / News', value: 'blog' },
            { label: 'Bewerbungsbereich', value: 'jobs' },
            { label: 'Shop / Buchung', value: 'commerce' },
          ],
        },
        {
          id: 'relaunch-target-date',
          key: 'targetLaunchDate',
          fieldType: 'date',
          label: 'Gewünschtes Ziel- oder Go-live-Datum',
          required: false,
          order: 2,
        },
        {
          id: 'relaunch-budget',
          key: 'projectBudget',
          fieldType: 'budget',
          label: 'Geplantes Budget / Rahmen',
          required: false,
          order: 3,
        },
        {
          id: 'relaunch-consent',
          key: 'privacyConsent',
          fieldType: 'consent',
          label:
            'Ich stimme der Verarbeitung meiner Angaben für die Projektanfrage zu.',
          required: true,
          order: 4,
        },
      ],
    },
  ],
};
