import type { IntakeTemplateDefinition } from '@/types/intake';

export const seoContentTemplate: IntakeTemplateDefinition = {
  title: 'Content- und SEO-Fragebogen',
  slug: 'content-seo',
  description:
    'Vorlage für Content-, SEO- und Seitenstruktur-Briefings mit Fokus auf Sichtbarkeit und Conversion.',
  status: 'active',
  version: 1,
  formType: 'seo-content',
  defaultLocale: 'de',
  notificationConfig: {
    internalRecipients: [],
    internalSubject: 'Neuer SEO-/Content-Fragebogen eingegangen',
    internalTemplateKey: 'intake-seo-internal',
    customerConfirmationEnabled: true,
    customerSubject: 'Dein SEO-/Content-Briefing ist eingegangen',
    customerTemplateKey: 'intake-seo-customer',
  },
  sections: [
    {
      id: 'seo-basics',
      title: 'Ausgangslage',
      order: 1,
      stepKey: 'basis',
      questions: [
        {
          id: 'seo-company',
          key: 'companyName',
          fieldType: 'company',
          label: 'Firmenname',
          required: true,
          order: 1,
        },
        {
          id: 'seo-website-url',
          key: 'websiteUrl',
          fieldType: 'url',
          label: 'Website-URL',
          required: false,
          order: 2,
        },
        {
          id: 'seo-primary-goal',
          key: 'primarySeoGoal',
          fieldType: 'radio',
          label: 'Was ist das Hauptziel?',
          required: true,
          order: 3,
          options: [
            { label: 'Mehr lokale Sichtbarkeit', value: 'local-visibility' },
            { label: 'Mehr qualifizierte Anfragen', value: 'more-leads' },
            { label: 'Bessere Inhaltsstruktur', value: 'content-structure' },
            { label: 'Relaunch vorbereiten', value: 'relaunch-prep' },
          ],
        },
        {
          id: 'seo-keywords',
          key: 'importantTopics',
          fieldType: 'textarea',
          label: 'Welche Themen, Leistungen oder Suchbegriffe sind wichtig?',
          required: true,
          order: 4,
        },
      ],
    },
    {
      id: 'seo-content',
      title: 'Content und Prioritäten',
      order: 2,
      stepKey: 'content',
      questions: [
        {
          id: 'seo-existing-content',
          key: 'existingContentQuality',
          fieldType: 'dropdown',
          label: 'Wie gut sind die bestehenden Inhalte nutzbar?',
          required: true,
          order: 1,
          options: [
            { label: 'Gut nutzbar', value: 'good' },
            { label: 'Teilweise nutzbar', value: 'partial' },
            { label: 'Muss weitgehend neu erstellt werden', value: 'rebuild' },
          ],
        },
        {
          id: 'seo-new-copy',
          key: 'newCopyNeeded',
          fieldType: 'yes-no',
          label: 'Sollen neue Texte erstellt werden?',
          required: true,
          order: 2,
        },
        {
          id: 'seo-priority-pages',
          key: 'priorityPages',
          fieldType: 'checkbox-group',
          label: 'Welche Seitentypen haben Priorität?',
          required: false,
          order: 3,
          options: [
            { label: 'Startseite', value: 'home' },
            { label: 'Leistungsseiten', value: 'services' },
            { label: 'Ortsseiten', value: 'locations' },
            { label: 'Branchenseiten', value: 'industries' },
          ],
        },
        {
          id: 'seo-files',
          key: 'seoDocuments',
          fieldType: 'file',
          label: 'Keyword-Listen, Inhalte oder Exporte hochladen',
          required: false,
          order: 4,
          validationRules: {
            allowMultiple: true,
          },
        },
      ],
    },
    {
      id: 'seo-planning',
      title: 'Timing und Einwilligung',
      order: 3,
      stepKey: 'planung',
      questions: [
        {
          id: 'seo-timeline',
          key: 'timelineExpectation',
          fieldType: 'text',
          label: 'Gibt es einen Zielzeitraum oder eine Deadline?',
          required: false,
          order: 1,
        },
        {
          id: 'seo-rating',
          key: 'urgencyRating',
          fieldType: 'rating',
          label: 'Wie dringend ist das Thema aktuell?',
          required: false,
          order: 2,
        },
        {
          id: 'seo-consent',
          key: 'privacyConsent',
          fieldType: 'consent',
          label:
            'Ich stimme der Verarbeitung meiner Angaben für die Projektanfrage zu.',
          required: true,
          order: 3,
        },
      ],
    },
  ],
};
